language: java

install: true

services:
  - xvfb
  - docker

addons:
  sonarcloud:
    organization: morganteg
  chrome: stable

cache:
  directories:
    - $HOME/.m2
    - $HOME/.sonar/cache

matrix:
  include:
    - jdk: openjdk8

script:
  - ./mvnw clean verify -Pjacoco
  - ./mvnw verify -Pe2e-tests
  - ./mvnw coveralls:report sonar:sonar