language: java
#jdk: openjdk8
install: true
addons:
  sonarcloud:
    organization: morganteg
cache:
  directories:
  - $HOME/.m2
  - $HOME/.sonar/cache
matrix:
  include:
  - jdk: openjdk8
    env: ADDITIONAL_MAVEN_ARGS="-Pjacoco coveralls:report sonar:sonar"
script:
  - mvn clean verify $ADDITIONAL_MAVEN_ARGS