language: java
install: true
services:
  - docker
addons:
  sonarcloud:
    organization: morganteg
  chrome: stable
cache:
  directories:
    - $HOME/.m2
    - $HOME/.sonar/cache
matrix:
  include:
    - jdk: openjdk8
    - jdk: openjdk9
script:
  - mvn clean verify -Pjacoco coveralls:report sonar:sonar