language: java
jdk: openjdk11
install: true
cache:
  directories:
  - $HOME/.m2
matrix:
  include:
    - jdk: openjdk9
      env: ADDITIONAL_MAVEN_ARGS="-Pjacoco coveralls:report"
script:
  #- mvn install -Dmaven.test.skip=true -Dmaven.javadoc.skip=true -B -V
  - mvn clean verify $ADDITIONAL_MAVEN_ARGS