version: '3'
services:
  mysql-service:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3316:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: deepskymanager
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 1s
      timeout: 3s
      retries: 30
    networks:
      - dsm-network
  app-server:
    image: openjdk:8
    ports:
      - 8080:8080
    volumes:
      - ./target/deepsky-manager-0.0.1-SNAPSHOT.jar:/app/app.jar
    command: java -jar /app/app.jar
    networks:
      - dsm-network
    depends_on:
      mysql-service:
        condition: service_healthy
networks:
  dsm-network:
    driver: bridge