version: '2'
services:
  mysql-service:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3316:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: deepskymanager
#    networks:
#      - dsm-network
#networks:
#  dsm-network:
#    driver: bridge