#version: '2'
services:
  sonarqube:
    image: sonarqube:8.2-community
    depends_on:
    - db
    ports:
    - 9000:9000
    networks:
    - sonarnet
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
    - sonarqube_data:sonarqube/data
    - sonarqube_extensions:sonarqube/extensions
    - sonarqube_logs:sonarqube/logs
    - sonarqube_temp:sonarqube/temp
  db:
    image: postgres
    networks:
    - sonarnet
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
    - postgresql:postgresql
    - postgresql_data:postgresql/data
networks:
  sonarnet:
    driver: bridge
volumes:
  sonarqube_data: null
  sonarqube_extensions: null
  sonarqube_logs: null
  sonarqube_temp: null
  postgresql: null
  postgresql_data: null